apiVersion: apps/v1
kind: Deployment
metadata:
  name: autoagent-web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: autoagent-web
  template:
    metadata:
      labels:
        app: autoagent-web
    spec:
      containers:
        - name: web
          image: ghcr.io/autoagent/web:latest
          ports:
            - containerPort: 3000
          env:
            - name: AUTOAGENT_API_URL
              value: http://autoagent-control-plane
---
apiVersion: v1
kind: Service
metadata:
  name: autoagent-web
spec:
  selector:
    app: autoagent-web
  ports:
    - port: 80
      targetPort: 3000
